- .gitignore
- .markdown-link-check.json
- .markdownlint.json
- README.md
- cspell.json
- link-check.js
- package.json
Tests added:
* Spelling
* Markdown lint
* URL validation
Fixed README.md lint
> Add tests to project

- .markdown-link-check.json
- README.md
- ReferenceMaterials/README.md
- TeamMandate/ArushiProposal.md
- TeamMandate/RemyProposal.md
- TeamMandate/RemyProposal_TeamCharter.md
- cspell.json
Added a series of tests and the exceptions (internal URLs, accepted dictionary words, etc.)
Fixed lint on files.
> Tests and Lint Fixes

- TeamMandate/Mandate.md
Manually merged changes from PR #18 and fix lint & typos
> PR18 merge

- cspell.json
Add a new exception word to dictionary.
> Update dictionary exceptions

- TeamMandate/Mandate.md
Inspired by a conversation with Arushi ... 
IT Strategy be responsible for a organizational Evolutionary IT Strategy fund
All projects run under this fund will run under our governance. Tool expenses and salaries will be run against the fund. We will grow the fund annually as we demonstrate success. 
Governance will start off largely non-existent and new ones will be created as need be as we scale up (more projects and responsibilities). 
Focus is on improving the organization by experimenting and sandboxing new approaches to benefit the organization. It differs from the innovation hub who is working on innovating new services. We are innovating governance within ESDC. 
Then all of our other points under mandates can be strictly enforced within our projects. Ex: Enforce use of JS on both …
> Proposing an umberalla fund 

- TeamMandate/Presentation.md
Adding a skeleton for a presentation for our vision 
Adding a document starting to list requirements for the proposed Umbrella funding
> template for vision presentation and Umbrella funding requirements

- Strategies/ITStrategyFullMobileProfile.md
- TeamMandate/Mandate.md
- TeamMandate/Presentation.md
- Creation of initial idea for fully mobile worker (skype for business does not actually work on phones?) 
- Updating mandate to take into account strategic umbrella fund 
- Changing format of presentation
> Umberall fund proposal

- Strategies/WebServicesAccess.md
This makes it more like something we can submit for approval for enabling access to Internet
> Add purpose, background, issue, consideration and next steps

- Strategies/WebServicesAccess.md
I think this is good, maybe a bit too long
> Update Consideration with more Business Value

- _includes/head.html
- _includes/header.html
- _layouts/default.html
- _layouts/splash.html
- _pages/index.html
> Remove list of pages from main menu - Fix HTML validation

- Strategies/ITVision.md
- cspell.json
3 pages :)
The IT Vision complements the HDLC story which is taken from the point of view of the citizen, and the KPIs which define the performance metrics needed to sustain the HDLC, by providing the point of view of the organization's IT capabilities.
It's basically a contextualization of the [GC's IT Strategy](https://www.canada.ca/en/treasury-board-secretariat/services/information-technology/strategic-plan-2017-2021.html#toc4) to ESDC's. Some additional, more ambitious wordings than the GC IT Strategy (on the Open by default, Cyber Security, and leverage of private sector).
The idea is that if this IT Vision is ratified, it would give us the ammos to meet other IITB/ESDC teams to start making changes as per the StrategySummary roadmap.
> Proposed IT Vision

- CONTRIBUTING.MD
- README.md
Update README with French
Add note on Contributing.md
> Fix readme

- cspell.json
- wip-tec/en/IITB_KPIs.md
KPI ideas for IITB Services + Add PCRA for project intake
> KPI Feedback

- wip-tec/en/WebServicesAccess.md
> WIP - Updates to WebServicesAccess.md

- _config.yml
> Change stand for stance

- _pages/en/it-picture-long-term.md
- _pages/en/it-picture-medium-term.md
Created two new documents in English (for now)
They contain the initial "views" that we had listed in #158 but many others can be added. We could also remove, combine in the future as we receive feedback.
Next steps would be to take the vision we have and create short bullet list of what it means for each view, describing it in "outcomes" (we've moved 50% of our load to public cloud would fit in IITB but end users wouldn't care for instance).
This can also be realigned with the Way Forward
> Create new working documents

- _pages/en/it-picture-long-term.md
- _pages/en/it-picture-medium-term.md
- cspell.json
Creating initial content for long term plan from a citizen perspective 
- Need to find data to validate claims
> creating initial content for citizen related long term picture

- _includes/preface-looking-forward.html
- Creating a layout that can be subtituted into our medium and long term plans 
- More information and data needed
> Preabme for our planning documents

- _pages/en/capabilities.md
- _pages/en/employee-profiles.md
- _pages/en/it-picture-medium-term.md
- cspell.json
Added 24 key capabilities that drive improvements in software delivery performance in a statistically significant way. From [Accelerate: By Forsgren, Humble & Kim](https://itrevolution.com/book/accelerate/).
Added our employee profiles since we will be referencing them in our visions and strategies.
Added TOC to medium term and removed leftover merge conflict text
> Add capabilities and employee profiles

- _pages/en/it-picture-long-term.md
- _pages/en/service-culture.md
Moved things around and added headers under modern open org based on capabilities.  Also removed numbers %
> Long term IITB vision update

- _pages/en/it-picture-long-term.md
- edited table of content
- added Private Sector bullet points (similar to Citizens)
- changed IITB-ESDC content
- added References section to lighten references throughout the document
> Editing changes for readability, and added some new content. See file changes for more

- _pages/en/service-culture.md
- cspell.json
There is a link in long and medium term to this document. The changes reflect the context in which they are referenced from the medium term document. 
- Outlining how security and testing should shift left to leverage automation and realize efficiencies
> Content update for service culture

- _pages/en/enable-learning.md
- cspell.json
Adding strategy as to what type of learning should take place and why
Perhaps should be moved into separate doc?
> Future Proof Learning 

- _includes/footer-revealjs.html
- _includes/footer.html
- assets/js/notes.html
- assets/js/notes.js
Closes #106 
I tried to use CDN for everything but the notes.js calls a notes.html page and it was trying to get it from the CDN and that can't work.
I added the notes js and html files to assets under js.  They need to be in the same folder unless we make a change to the js file and I prefer not to do that since it will be easier to upgrade.
I made a small change to the notes.html file to load the marked plugin from CDN instead of trying locally, since it's not there.  It was working without it be getting an error in console
> Add Revealjs Notes plugin - Update Jquery

- _config.yml
- _includes/listPages.md
- _includes/listPosts.md
- _includes/listPresentations.md
Updated the include listPages.md to automatically group by categories.
If no category is specified (needs to be a listed category), the page will not be displayed.
> Categories

- _pages/en/mandate.md
modified mandates slightly to clarify focus of work
added sub section on defining what Digital Transformation is
> changed mandate to focus on reducing risk of doing IT

- _config.yml
- _pages/en/mandate.md
- _pages/fr/mandat.md
PLEASE TEST JEKYLL before merge
I tried using labs.play-with-docker.com but am getting Connection Error.
> Remy change site sub title for updated mission

- _pages/en/it-picture-medium-term.md
- cspell.json
- about hardware provisioning (e.g. laptops)
- process: governance and capability-based planning by EA (this is
important)
- technical: device provisioning and network bandwidth
- measurement: SRE, APM, device provisioning transparency, and business
lines requirement to allocate budget to deal with system lifecycle
> Added some statements:

- _pages/en/it-picture-medium-term.md
- One sentence per line
- Link to mandatory EA procedures
- Reword to be less dev focused
- Flow of work
- ..
> Medium cleanup

- _includes/header.html
I was just cleaning up before trying to find the issue but I think this fixes #252
> Menu - Remove whitespace in HTML output

- _pages/en/it-picture-medium-term.md
As usual, fully open to feedback and changes :)
> Medium Term Updates

- _includes/footer.html
> Fix mobile menu (jQuery blocked because HTTP link)

- _pages/en/references.md
- cspell.json
Adding video resources for innovation / security
> Updating resources

- _posts/en/2019-10-15-case-continuous-improvement.md
> Fix typos in blog case for Continuous Improvement

- _posts/en/2019-10-15-case-continuous-improvement.md
Had to fix how the area was calculated (I said the area between the curves was actually the area under f(x))
> Case for continuous learning fix

- _posts/en/2019-10-15-case-continuous-improvement.md
Typo fix and moving a context setting parapraph
> spelling errors and moving a paragraph

- _pages/en/it-picture-medium-term.md
More work needed but at least all links are embedded or moved to an **Additional reading** section.
Resolve #290
> Embed Medium Term Picture Links

- .editorconfig
- package-lock.json
- package.json
Updated NPM package `markdown-link-check` that updated `marked` that had a vulnerability.
Added npm audit to build to see how it works.
Changed licensee to only show licences if there are errors
> Npm update marked

- _config.yml
- _includes/listPages.md
- _pages/en/building-enabling-directorate.md
- _pages/en/capabilities.md
- _pages/en/digital-identity-timeline.md
- _pages/en/employee-profiles.md
- _pages/en/how_to_contribute.md
- _pages/en/human-development-life-cycle.md
- _pages/en/iitb-kpi.md
- _pages/en/it-picture-long-term.md
- _pages/en/it-picture-medium-term.md
- _pages/en/mandate.md
- _pages/en/quarterly-delivery.md
- _pages/en/references.md
- _pages/en/service-culture.md
- _pages/en/speaking_notes.md
- _pages/en/strategies-actions.md
- _pages/en/strategy-summary.md
- _pages/en/transition-to-partner.md
- _pages/en/trends.md
- _pages/en/web-services-access.md
- _pages/fr/comment-contribuer.md
- _pages/fr/dgiit-ipc.md
- _pages/fr/mandat.md
- _pages/fr/references.md
- _pages/fr/retroaction-strategie-it.md
- _pages/fr/sommaire-strategie.md
- _pages/fr/tendances.md
CAREFUL: Please review thoroughly as this change could break the site structure.
(Note: it is uncommon to change this many files at the same time as it my have ripple effect on other's work)
> Change Categories tag to Sections

- _config.yml
- _includes/listPresentations.md
> List presentations based on files

- _pages/en/enable-learning.md
- _pages/en/strategies-actions.md
other than changing the first section, I reordered to put the general statements before the "IT teams must.." statements
> Update GC IT direction section - move some things

- presentations/en/GCcode-version-control-system-esdc-gc.md
> CIOEC GCcode presentation

- presentations/en/2019-11-05-Working-in-the-open.md
- presentations/en/2019-11-12-OSS-Contributing.md
- presentations/en/2019-11-12-OSS-Using.md
> Fix instruction links

- .markdown-link-check.json
> added youtube and trello as ignorePatterns

- .markdown-link-check.json
Fix test on gccode which is on Intranet only.
> Exclude gccode URL from test

- presentations/en/2019-11-05-Working-in-the-open.md
Updated my presentation.
Audience is diverse: devs, data scientists, designers, etc.
Shouldn't be too technical.
> Add subtitles and update notes

- presentations/en/2019-11-05-CIOEC-Mandate.md
after rebasing from master
see the actual presentation change here
https://sara-sabr.github.io/util-presentation/presentation.html?url=https://raw.githubusercontent.com/sara-sabr/ITStrategy/CIOECMandatePresTweaks/presentations/en/2019-11-05-CIOEC-Mandate.md
> Cioec mandate pres tweaks

- presentations/en/2019-11-05-CIOEC-Mandate.md
> removing brackets as per requested via email

- _includes/footer.html
- _includes/head.html
I was testing tables on the website and found this solution to add missing classes.
Fixes #346
> Add bootstrap class for table and blockquote

- presentations/en/2019-11-12-OSS-Contributing.md
Added link to small project
Added Twitter handle
> Update Contibuting presentation

- _pages/en/exercises-automation-npm.md
- cspell.json
- presentations/en/2019-11-12-OSS-Publishing.md
- presentations/en/2019-11-12-OSS-Using.md
Small explanation on how to add tests to a project.
> Automation Exercises

- _layouts/post.html
Simplified the validation logic on post modified date.
If there's a tag `modifiedDate` in the front matter, it'll automatically trigger the paragraph.
> Simplify modified date logic

- _layouts/default.html
> Fix duplicate last modified date

- _includes/head.html
Closes #272 
Add google analytics tag to see if it works
> Add global site tag (gtag.js)

- _pages/en/strategies-actions.md
Closes #414 
I'm thinking we should have a date on this to say that these are the strategies for FY19-20 Q4 (late for Q3) and that the strategies will continuously evolve each quarter.
Todo
> Update strategies-actions.md (add/regorg)

- _posts/en/2019-11-19-working-in-the-open-part-1.md
- _posts/fr/2019-11-19-travailler-ouvertement-partie-1.md
Traduction du billet "Working in the open"
> Blog travail ouvert

- _pages/en/strategies-actions.md
adding in creation of Devops Dojo
> Add in creation of Devops dojo

- _pages/en/esdc-it-strategy.md
removed a sentence that reference our old strategy map's pillars
> removed mention of old strategy map pillars

- _pages/en/web-services-access.md
- cspell.json
Comments to address:
I struggle with how DLP figures in to this.  Although I understand we would use it to limit data loss etc… it seems that as the first Item in issues that this is about DLP. Maybe it could be part of the mitigation strategies on how to reduce risk?
We refer to the need to open up access to services to support GOC policy and employee Internet accessibility above.  The Issues don’t feel like they line up well to the purpose.  I like the fact that we are saying we are already doing it but don’t grasp what we are trying to highlight as an issue.
Good do we have any non TBS or digital academy references we could add? (using Google drive, Docs, ..)
Reference DLP here as a risk mitigation item
Is there value in adding a column that would explain benefits of use?  When I see …
> Changes based on feedback (Access to SaaS)

- _pages/en/employee-profiles.md
- cspell.json
Add content to the WIP Employee Profile page. (English only at the moment).
Few things:
- Initial list doesn't match new list of profiles
- There seems to be empty profiles.
> Employee profiles

- _pages/en/communications-plan.md
- _pages/en/strategy-communications.md
- cspell.json
I tried to list the approval process and ways we can use for outreach and gathering feedback.
Related to #473
> First draft communications strategy

- _posts/en/2019-12-20-why-we-are-promoting-risks.md
- _posts/fr/2019-12-20-pourquoi-nous-favorisons-les-risques.md
- Change blog post to 1st person plural
- Make clarification about need for governance bold and on its own paragraph
- Add notes about changes
> Change blog post to 1st person plural

- _pages/en/strategy-communications.md
De nos conversations de ce matin sur le planning des communications
> added more bodies like CIOEC, Comms, Change Management

- _config.yml
- _includes/listPresentations.md
> Fix FR presentation print version link

- presentations/en/SLF.md
- presentations/fr/SLF.md
Last slide in the presentation
- EDSC.DGIIT.StrategieTI-ITStrategy.IITB.ESDC@hrsdc-rhdcc.gc.ca
- https://sara-sabr.github.io/ITStrategy
- https://sara-sabr.slack.com
French view: http://ip172-18-0-9-boorc1033cq000frl97g-4000.direct.labs.play-with-docker.com/ITStrategy/presentation.html?markdown=fr/SLF.md
English view: http://ip172-18-0-9-boorc1033cq000frl97g-4000.direct.labs.play-with-docker.com/ITStrategy/presentation.html?markdown=en/SLF.md
> Added one more slide for SLF Presentation: contact us (english and french)

- .github/ISSUE_TEMPLATE/accessibility-issue.md
Create an accessibility issue template, to help track and triage accessibility issues
> Create an accessibility issue template 

- _layouts/splash.html
- _pages/index.html
- assets/css/style.css
resolves #729 
resolves #728 
Desktop
Mobile
> Splash page accessibility

- _pages/presentation.html
resolves #732 
resolves #733 
- Dynamically add title element and lang attribute from markdown parameter
> title element and language attribute

- _pages/en/buy-vs-build-strat.md
- _pages/en/quarterly-delivery.md
resolves #737 
resolves #738 
resolves #718
> added alt text for images

- _pages/en/strategy-learning-automating-improving.md
- cspell.json
Move Improve before Learn
Move Goals before Actions
> Q1 Strategy - move words

- .travis.yml
- get-link-from-path.js
- list-links.js
- package-lock.json
- package.json
Automation of accessibility checks using axe CLI
resolves #653
> Automation of accessibility checks

- _pages/en/strategy-learning-automating-improving.md
- cspell.json
Incl. minor edits
Feel free to add more references!
> Add references to Continuous Learning Strategy

- _pages/en/strategy-learning-automating-improving.md
> Make case for 20 improvement

- _pages/en/strategy-learning-automating-improving.md
I hope this is what you were expecting @jaysonmc
> Adding learning with devcop

- _pages/en/strategy-learning-automating-improving.md
If anyone else knows of any other CATS codes that could apply to what we have listed, I think that would help folks
Linked to issue #850
> Continuous improvement update

- .markdown-link-check.json
- _pages/en/references.md
- cspell.json
- [Hack Chat](https://hack.chat)
- [Gitter](https://gitter.im)
#874
> Two Im tools missing names (only links were there)

- _pages/fr/strategie-amelioration-apprentissage.md
Changer la section pour la page en français pour qu'elle apparaisse sur la page avec nos documents.
> Fix section Stratégies trimestrielles

- _includes/header.html
closes #884 
Add code to show language picker for blogs posts
> Show language toggle for blogs

- _pages/en/strategy-communications.md
- cspell.json
Additional information/references if needed
> Additional information for communication strategy

- _pages/en/it-picture-long-term.md
- _pages/en/it-picture-medium-term.md
- _pages/fr/perspectives-ti-long-terme.md
- _pages/fr/perspectives-ti-moyen-terme.md
- cspell.json
Received texts from translation.
Closes #892
> Add translated IT pictures

- .markdown-link-check.json
- _config.yml
- _includes/footer.html
- _includes/header.html
- _includes/listPages.md
- _includes/notice.html
- _layouts/default.html
- _pages/en/archives.md
- _pages/en/home.md
- _pages/en/how_to_contribute.md
- _pages/en/strategy-learning-automating-improving.md
- _pages/en/strategy-summary.md
- _pages/fr/accueil.md
- _pages/fr/archives.md
- _pages/fr/comment-contribuer.md
- _pages/fr/sommaire-strategie.md
- _pages/fr/strategie-amelioration-apprentissage.md
- _posts/en/2020-04-21-how-is-the-public-service-managing-large-IT-project.md
- cspell.json
- Remove notice and add modal message with link in footer
- Archive some pages (How to contribute, Q1 and Strategy Map)
- Remove Mandate from every page
- Remove some words and links from Home page
- Change green to blue (info alert)
- Add Archive section to list archived pages
> Change to Website based on ROT analysis

- _pages/en/buy-vs-build-strat.md
> Archive User Build vs Buy page

- _posts/en/2020-04-21-how-is-the-public-service-managing-large-IT-project.md
- Fixed Excerpt (whole post was in the excerpt of the Blog list)
- Added a few return of line where multiple sentences were on the same line.
> Blog project fix excerpt

- _pages/en/strategy-build-vs-buy.md
Forgot to update version number and change log
> Buy build fix version0.03

- _data/i18n/general.yml
Simple commit to move site related data to a data file, specifically around i18n.
> Site Structure - Move config data to data file

- _pages/en/strategy-build-vs-buy.md
Small change to include the link to the internal workspace.
> Add link to internal workspace material

- _pages/en/capabilities.md
Replaces #1031 
Reuse old page with DORA capabilities. Moved it out of Archives into Work in progress.
For each capability, start adding Outcomes, Indicators, Goals and Actions how to improve.
Started for Version control, CI, Streamlining change approval and Westrum.
Instead of putting in a maturity model way (Low, Med, High or Crawl, Walk, Run), I just put the Goal for IITB. So just High or Run.
Based on Work started for #981
>  Update Capabilities page with Outcomes and Indicators (2)

- _pages/en/GCDevelopers-Exchange.md
- _pages/fr/carrefour-programmeurs-gc.md
- presentations/en/2019-11-05-Working-in-the-open.md
- presentations/en/2020-01-22-Working-in-the-open.md
> Fix Build - Remove dead links

- _data/tables/transform-high-performing-org.yml
- _pages/en/strategy-transform-high-performing-org.md
Transfered from Etherpad
Closes #1090
> Transform into high performing Org - version 0.01

- .licensee.json
- .travis.yml
- _pages/en/enable-learning.md
- package-lock.json
- package.json
> Remove axe-cli from travis build and Fix link to pdf

- _pages/en/strategy-build-vs-buy.md
* Update version + date
* Remove authoritative mention
> Build vs Buy - Minor update

- _data/tables/build-vs-buy.yml
- _pages/en/strategy-build-vs-buy-explained.md
- _pages/en/strategy-build-vs-buy.md
Modified:
- Coherent actions table now has a lead identified separately
- Date updated
- Modified "Obtention" references to "Obtaining" in sub header as per disposition comments.
> ABB - v0.05 adjustments pre-review

- .markdown-link-check.json
- _pages/en/capabilities.md
- Standard format for sections, questions, scoring and recommendations
- Types of questions listed at the top (3 types)
- Some questions in Process, I think are more based on the how to improve the capabilities.  We could keep those for recommendations.
> Update/review questions for Technical and Process capabilities

- _pages/en/strategy-build-vs-buy.md
> Abb alt text

- presentations/en/2020-Micro-procurement-pilot-DG-Comm.md
(mostly). A few other minor changes too.
> Updates to next steps and speaking notes (micro-procurement deck for DG Comm)

- _includes/footer.html
- _layouts/default.html
- _pages/en/it-picture-medium-term.md
Issues found using AxE accessibility Add-on in Firefox. 
- Remove aside from inside main
- Fix header levels
- Enable focus on code blocks (Closes #715, Closes #727)
> Fix AxE Best practice issues

- _pages/en/capabilities.md
> Assessment tool updated questions

- _pages/en/capabilities.md
Take questions from the DORA self assessment and merge with our questions.
I added a generic : Please rate how strongly you agree or disagree with the following statements. On my team: ..
and removed mention of my team in each statement.
> Merge more DORA questions

- _pages/en/capabilities.md
Added description for each capability. 
#1406
> Section description (Assessment tool)

- assets/css/style.css
Some images were not responsive on our website. This small change makes them all responsive.
> Make all images responsive

- _posts/en/2019-10-15-case-continuous-improvement.md
Blog post had H1 --> H3 --> H2 order.
this fixes the H3 to H2.
> Fix headers

- _data/tables/references.yml
A very kind visitor suggested that we update the IM tools of our Resources page (thank you!)
- Removed WhatsApp
- Added Telegram, Threema and Wire
- Reordered (thus why the diff changes are all over the place)
> Update IM tools

- _data/i18n/general.yml
- _layouts/default.html
- _pages/fr/auto-evaluation-devops.md
Fixes #1635 - lien pour Auto-évaluation DevOps en français 
Closes #1453 - remove mandate from header
> Website changes and fixes

- _data/i18n/general.yml
- _includes/blog-nav.md
- _layouts/post.html
Adds buttons to blogs, to navigate to previous and next blog post.
Example
Closes #1465
> Add blog post navigation (previous, next)

- _includes/header.html
(same as PR #1636 but for all the other pages)
**Actions**
1. Information message shown (depending on language of the site being viewed) :
English:
> We recommend to use Edge, Firefox and other modern browsers instead of Internet Explorer.
> 
> We'll now open this website in Edge for an optimal experience.
French:
> Nous recommandons d'utiliser Edge, Firefox et autres navigateurs modernes au lieu d'Internet Explorer.
> 
> Nous allons maintenant ouvrir ce site dans Edge pour une expérience optimale.
2. Edge launched and same page opened (presentation)
3. This page opened by Internet Explorer (now in the background):
[The website you were trying to reach doesn't work with Internet Explorer](https://go.microsoft.com/fwlink/?linkid=2135547)
Feel free to tweak and merge 👍
> Redirect all pages opened with Internet Explorer 11 to Edge

- _pages/en/devops-self-assessment.md
- _pages/fr/auto-evaluation-devops.md
> DevOps Self-Assessment website page update

- _data/members.yml
Updated my bio text to something that is more representative. :-)
> update to Rachels bio

- _data/i18n/general.yml
- _layouts/default.html
> Add notice on archived pages

- _pages/en/strategy-open-first.md
- cspell.json
Need more background on Open government in GC and ESDC..
Closes #1759
> Draft Current situation, Add TOC, Fix Build

- .github/ISSUE_TEMPLATE/accessibility-issue.md
- .github/ISSUE_TEMPLATE/joint-councils-oss-wg---conseils-mixtes-logiciels-libres.md
Add a new template for JC OSS WG
> Update issue templates

- _data/members.yml
Hey @gcharest! I know you don't care about this stuff but I feel like your title on the team page should reflect your recent promotion.
Feel free to close this PR if you'd rather leave your title as is. :)
> Update Guillaume's title in the About Us page

- _pages/en/micro-acquisition-pilot.md
- _pages/fr/pilote-de-micro-acquisition.md
Banner includes a link to the micro-acquisition website and the date the pilot will end.
> Added a banner to the MA page

- _pages/en/strategy-open-first.md
- cspell.json
Edits by @LeighGardner.  Some changes by me.
> Mostly Wording changes

- _pages/en/strategy-open-first.md
I made very good progress on my thorough review of the Open First Strategy, but I don't consider it fully completed yet.
I'll continue when I'm back in 1 week (Sept. 7) if that's ok.
But feel free to review and merge if you would like these changes to be live quickly.
> Open First Strategy review (draft PR)

- _pages/en/strategy-open-first.md
Sections numbering was not sequentials
> Fix number of sections

- _posts/en/2021-10-15-product-management-part-2.md
- _posts/fr/2021-10-15-gestion-de-produit-partie-2.md
Forgot to fix publication date on the blog post.
> fix: Update post publication date

- _data/i18n/general.yml
- _includes/listPresentations-decks.md
- _pages/en/presentations.md
- _pages/fr/presentations.md
changed presentations.md to add link to static files like PPTX
> Added the english and bilingual PPTX used for Product Management

- .github/workflows/github-project-export.js
- .github/workflows/github-project-export.yml
Hi folks!
Just trying the automated data export script I've been working on on my end!
It's currently scheduled to run every weekday morning at 7:30.
The format matches @LeighGardner last data export format so unless you have made changes, it should provide you with the proper data extract every day!
Guillaume
> GitHub project export

- _pages/en/product-fw-directive.md
- _pages/en/product-fw-guidance.md
- _pages/en/product-fw-procedures.md
- _pages/en/product-fw-standard.md
- cspell.json
1st peer review was completed. this PR publishes the changes that was made to it.
> Updates to the Product Mgt Framework after 1st peer review

- _posts/en/2021-05-18-problems-of-project-based-funding.md
- _posts/en/2021-10-15-product-management-part-2.md
- _posts/fr/2021-05-18-problemes-financement-par-projet.md
- _posts/fr/2021-10-15-gestion-de-produit-partie-2.md
Fixes some blogs, others still need fixing..
Related to #2021
> Fix style of images to not overflow when in mobile view

- _includes/blog-nav.md
> Reverse Pervious and Next links for blog navigation

- _data/i18n/general.yml
- _includes/footer.html
- _includes/head.html
- _pages/en/privacy-disclaimer.md
- _pages/fr/clause-confidentialite.md
- cspell.json
relates to issues #2380 and #2379
> Google analytics 4

- .markdown-link-check.json
- _pages/en/archives/strategy-learning-automating-improving.md
- _pages/fr/archives/strategie-amelioration-apprentissage.md
- changed "https://idp.csps-efpc.gc.ca/" to "https://www.csps-efpc.gc.ca/"
- put "https://gcxgce.sharepoint.com/" in the ignore list
> Fixed two broken links

- _includes/head.html
New code was already there and good.  Only removed the old code and added Tab for new one.
#2543
> Remove old GA code.  Indent new code

- .github/workflows/link-check.yml
- package.json
Hey @smellems will this work? I'm trying to set up an action to run weekly to check for deadlinks on the website.
I couldn't test it locally - scheduled actions can't be tested in forked repos or local branches.
> Aded workflow to check dead links

- LICENSE
- _includes/footer.html
- assets/css/style.scss
CSS changes
* Add more space between footer items
* Add • between each footer item
* Change footer display from row to column for medium and small screens
* Update image size for medium screen to span width of parent container
* Update table layout for medium and small screens to become scrollable
Other changes
* Remove copyright text in footer
* Update copyright text in license
> Update css for table, image, and footer for medium and small screens

- .github/workflows/node.js.yml
- Gemfile
- data.json
node.js.yml
- Update origin so changes can be pushed to the main branch
Gemfile
- Locked ffi to 1.16.3 to address the issue with rubygem incompatibility when gh-pages action is ran
> Update GitHub actions
