sara-sabr/ITStrategy

_includes/footer-revealjs.html
_includes/head-revealjs.html
_layouts/revealjs.html
_pages/presentation.html
presentations/en/2019-05-28-Working-in-the-Open.md

I added a layout for reveal JS with a test presentation in a presentations folder.  It's get everything from CDN so we should be able to use it for all presentations.
I created a page to load presentations. You tell it the one you want in the URL
To test it go to `/ITStrategy/presentation.html?markdown=en/2019-05-28-Working-in-the-Open.md`
It's easy to break so maybe don't merge it yet

WIP - Add RevealJS layout and test presentation

---

_pages/en/it-picture-long-term.md

The way it was written implies a static perception of privacy and was too blanket. 
If we have a digital ID, we have a digital ID. And if you want to be paperless, we use that digital ID. So, for taxes or medical appts, that's just what you use, perhaps opting out is not a feature. 
For automated EI enrollement where the bank would exchange certain information with the government to be able to send you money, that could be an opt-out system. 
I would also propose it'd be best to make it an opt-out system rather than an opt-in one (if legally permitted, obviously. I'm talking from a digital effeciency perspective). My intuition would be, more people would want it, but not opt-in, than the amount of people who don't want it and would opt-out (the few technical people who care enough to do …

Changing phrasing 

---

_includes/footer.html

Related to #228
This works well for pages but for drawings, timelines also links to the page.
ex.: https://github.com/sara-sabr/ITStrategy/blob/master/_pages/en/digital-identity-timeline.md

Link to actual page on Github

---

_pages/en/capabilities.md
_pages/en/employee-profiles.md

This way we can link to those pages from the medium/long term pictures
Also updated the capabilities with the latest from DORA instead of the Accelerate book.

Add front matter for capabilities and profiles pages

---

.editorconfig
.licensee.json
package-lock.json
package.json

Edit: this does a few things
Add [Editorconfig](https://editorconfig.org/) config file and editorconfig-check to the build
Add Licensee to check if licences of dependencies are OSI or others listed in the `.licensee,json` file.  the config file also includes packages that have a licence but the format in package.json is out of date or it's an older version not updated in the parent package.
These checks are now part of the build and will run with `npm test`.
Also added license-compatibility-checker and site-validator-cli.  These need to be run individually for now.
- `npm run licence-compatibility`
- `npm run site-validator`
Important: Site validator will run on the current live site (sara-sabr.github.io), not localhost.
You can also use `npm run other-tests` to run only the tests not in …

Add licencee to build to check for valid OSI licences

---

_pages/en/mandate.md

Our mission statement must have de-risking the use of IT
It's the whole "transformation" in the digital transformation. As mentioned in War & Peace & IT
quote from page xxvi
> Now is the time to start transforming, because it's both low risk and urgent. You might be surprised that I say it's low risk, but I insist. Enterprises may feel like they should move slowly and cautiously, stepping onto the digital path only after they've checked the traffic coming from all directions.
> But the very point of digital transformation is to *reduce* risk. 
> Digital enterprises set risk-mitigating guardrails in place, then use their speed as a way to quickly adjust course when new risks appear.

re-added risk in the mission statement

---

_config.yml
_pages/en/building-enabling-directorate.md
_pages/en/capabilities.md
_pages/en/esdc-it-strategy.md
_pages/en/it-picture-long-term.md
_pages/en/it-picture-medium-term.md
_pages/en/speaking_notes.md
_pages/en/strategies-actions.md
_pages/en/strategy-summary.md
_pages/fr/dgiit-ipc.md
_pages/fr/retroaction-strategie-it.md
_pages/fr/sommaire-strategie.md

J'ai changé les sections pour mettre le contenu "à la bonne place" L'idée est d'utiliser les bonnes sections pour avoir les "statut" des documents sur le site plus clairs.
Tout ce qui est `Travail en cours` devrait essentiellement être un brouillon, l'Image de la TI est les documents qui nous avaient été demandés, etc.
On pourrait créer d'autres sections au besoin pour ce qui est d'autres sortes de documents matures.
Règle le problème #300

Sections update

---

_config.yml
_includes/versioning.md
_layouts/default.html

Added version and date on documents.
Only displays if the document is in section "Ready to use" and either of the following tags are added in the front matter:
- `date:`
- `version:`
Following PR #407 comments from @remyb2canada

Versioning

---

_includes/header.html
_layouts/default.html

This moves the notice from the top of the page to the bottom.  Makes for less scrolling when you get to a page.

Move notice above footer

---

_pages/en/strategy-learning-automating-improving.md

Keep it simple.  2 sections: Actions and Goals.
Guidance for each action in a table.

Remove planning information from Q1 strategy page

---

_pages/en/strategy-learning-automating-improving.md
cspell.json

As discussed I removed Automation from the action for the Q1 strategy.
I also updated the list of guidance based on discussion.  I changed it back to a list from a table to make it easier to comment and edit.  We can always go back to a table for better presentation later.
We should rename the file name and permalink, but that would break links we shared already

Update Q1 strategy actions guidance

---

presentations/en/SLF.md

Quick change before dry run.  This removes Automate from the Q1 actions.

Remove automate from Q1 - update metrics guidance

---

_includes/header.html
assets/css/style.css

Tested Website using https://addons.mozilla.org/en-CA/firefox/addon/wave-accessibility-tool/
Fix error with the home logo not having a label. And removed extra HTML `</li></a>` from the same line
Applied the style for links in paragraph to all links in main content.  This does not affect the header or footer.  But the notice is part of main and the PR change the link color from the default alert color to blue.

Fix easy accessibility errors found with WAVE

---

assets/css/style.css

resolves #714 #740 #741 #720 #723 #731 
- Override bootstrap style for code element to comply with WCAG 2.0 AA colour contrast standard

resolved code highlighting color contrast

---

_pages/en/strategy-learning-automating-improving.md

Updates before sharing with Director (#534)
- Add Q1 to title of page and details on what Q1 2020 is.
- Links to IT Picture 2025 and Strategy Map.
- Remove ALL and MUST.
- Add "up to" 20%.  Since its now "should" and for teams that can't do 20%
I would like to change the filename and permalink, to remove automating, but the link has already been shared with some groups

Updates to Q1 Strategy

---

wip-tec/en/ITVision.md
wip-tec/en/citizen-partners-picture.md

These are old files but PCTF Website was updated with version 1.1 making the build fail

Fix Pan-Canadian Trust Framework link

---

assets/css/style.css

Because we have a fixed navbar, linking to an HTML page anchor scrolls too far down (anchor is hidden by navbar).
With this fix, we can link to headers (1-6) and scrolling works as expected. And the new CSS doesn't seem to change the visual aspect of headers.
Open to a better workaround of course :)

Fix anchor scrolling

---

_pages/en/esdc-it-strategy.md

Somehow using a markdown image tag makes the image too big.... just switching it to an HTML <img> tag even using 100% width/height fixes it...

Fixed logic model image size (to fit in the text width)

---

_pages/en/esdc-it-strategy.md

Two corrections:
1) Changed wording in the section "Program Statement"
Original wording made it sound like the problem is that we have too many applications in our portfolio. It wasn't the intent. The intent was to raise awareness on the increasing complexity technology (and departments) are facing. 
2) Corrected display of numbered list under Short Term Outcomes

It strategy corrections

---

presentations/en/2019-11-05-Working-in-the-open.md
presentations/en/2020-01-22-Working-in-the-open.md

The link is also wrong on their site since an update.  They might change it to lowercase..
Related issue: 18F/product-guide/issues/124

Fix Build - 18F link

---

_config.yml
_pages/en/esdc-it-strategy.md
_pages/en/human-development-life-cycle.md
_pages/en/it-picture-long-term.md
_pages/en/it-picture-medium-term.md
_pages/en/strategies-actions.md
_pages/en/strategy-learning-automating-improving.md
_pages/en/strategy-summary.md
_pages/fr/sommaire-strategie.md
_pages/fr/tendances.md

Closes #844 
This replaces "Ready for use" with a "Strategies" category on the Documents page.
I also added a "Done Enough" category.
I archived the Strategies and Actions page.  are there other pages we could move from "Work in Progress" to "Archive"?

Add Strategy and Analysis sections for Documents page

---

_includes/header.html

About us disapeared from the menu (became Vision) during the reorg of sections on the site.
PR adds it back.
This is what it looks like

Readd About us to menu

---

.markdown-link-check.json
package-lock.json
package.json
wip-tec/en/citizen-partners-picture.md

Removing npm audit from the test will fix the build.  Closes #984 
There is still a out of date dependency in site-validator-cli, waiting for one of its dependencies.
https://github.com/p1ho/site-validator-cli/issues/104

Run npm upgrade and fix build

---

.markdown-link-check.json

Temporary fix the link tests failing with surveymonkey (down for maintenance) and pm.gc.ca (no server response?).
Reverse fix will need to be performed shortly

Add temporary exception to surveymonkey

---

_pages/en/strategy-target-solution-delivery-model.md

There was a link supposed to be pointing to Directive on Project Management that was leading to the Programme Management instead.
Fixes that issue.

Fix URL pointing to Programme

---

_pages/en/web-services-access.md

Removed content with the dead link to the ESDC corporate code of conduct (which has been removed from canada.ca).
"and ESDC Code of conduct in particular Section D) Stewardship on the use of Electronic Networks"
https://www.canada.ca/en/employment-social-development/corporate/code-conduct.html

Update web-services-access.md to fix the broken link to the ESDC code of conduct

---

_pages/en/strategy-target-solution-delivery-model.md

As per discussion with IT Research, adding action to create DevOps CoE responsible to enable and implement the SDM strategy.

Add devops coe as action

---

presentations/en/2020-Micro-procurement-pilot-DG-Comm.md

includes: re-orienting to micro-procurement pilot rather than 'gcdevex', and ensuring next steps reflect that first we need approval then start the pilot.

updates to the micro-procurement deck

---

_includes/head.html

More details from Google if you are interested: [IP Anonymization (or IP masking) in Analytics](https://support.google.com/analytics/answer/2763052)
Related to #296

Enable website analytics IP anonymization

---

_config.yml
_includes/page-redirect.md

these changes required in order to add a redirect on the old Micro-procurement page (to point to the new Micro-Acquisition page).

Add page redirect functionality to site

---

_posts/fr/2020-12-04-meilleure-technologie-grace-au-micro-approvisionnement-partie-2.md

Minor fix - blog excerpt was not showing up on the nos billets page for the partie2 blog post on micro-procurement.

fix to the blog excerpt

---

_pages/en/web-services-access.md

Closes #1376 
This updates the list of sites that are blocked and not blocked and moves the page to the Archives on the Website.
Sites under IM, Document editing and Web conferences are now mostly unlocked.
Email and File sharing are still mostly blocked.

Update sites blocked - Move to Archives

---

README.md

With #1435 CI now uses Github Actions.
This updates the build status badge in the readme

Update badge from Travis to Github Actions

---

_includes/head.html

Closes #1401 
Quick fix to remove warning about mathjax cdn being retired (since 2017).

Change MathJax CDN to jsdelivr

---

_pages/en/web-services-access.md

https://drop.infini.fr has not been responding for more than a week.
MxToolbox report
https://mxtoolbox.com/SuperTool.aspx?action=a%3ainfini.fr&run=toolpage
> DNS No Valid NameServers Responded
Propose removing as not critical resource for us.

Remove dead service from file storage list

---

_pages/en/micro-acquisition-pilot.md

Added some content to this page to help address the 'what about' questions we often hear with Micro-Acquisition.  Thinking about also adding links to some of the pieces (e.g. the draft one page IP document and the draft processes). 
Interested in your thoughts.. does this capture the things you have heard/been asked most about MA?

Add a 'How we are minimizing risks' section to MA page

---

_includes/footer-revealjs.html
_pages/presentation.html

You can test in my fork (as Jekyll doesn't render presentations locally correctly anyway):
https://gabrielcossette.github.io/ITStrategy/presentations.html
Explanation: The native Web API "URLSearchParams" isn't supported by Internet Explorer.
I replaced it with a "[polyfill](https://en.wikipedia.org/wiki/Polyfill_(programming))" I found (while learning what is a polyfill at the same time 😄)
Fixes #1628

Fix presentations in IE

---

_pages/fr/auto-evaluation-devops.md

La page d'accueil de l'outil devops présente l'URL séparément du texte car il y a un espace entre ] et (.

Fix url format in FR version

---

_data/i18n/general.yml

As mentioned, I believe `Blogue précédent` and `Prochain blogue` actually be `Billet précédent` and `Prochain billet`
Refs: 
- http://bdl.oqlf.gouv.qc.ca/BDL/gabarit_bdl.asp?id=5383
- http://bdl.oqlf.gouv.qc.ca/BDL/gabarit_bdl.asp?id=4925

Change blogue for billet

---

.github/ISSUE_TEMPLATE/micro-acquisition

Saw that @gcharest had created a template for the joint council work and thought it would be awesome to have a template for MA issues.

Create micro-acquisition issue template

---

.github/ISSUE_TEMPLATE/micro-acquisition.md

I created a template last week for MA issues but the template isn't showing up in the 'New Issues' page (but it can be found by clicking on 'Edit Templates'). Hoping this PR adds it to the New Issues page (this time I created it via settings directly on the New Issues page). FYI I don't know what I'm doing. lol

Update issue templates - adding MA template

---

_data/tables/references.yml
_pages/en/resources.md
_pages/fr/ressources.md

closing #1629 
Resources page:
@smellems   can you please add to each link that is only ESDC network ‘ESDC network’ label.
and if a link is only in English add ‘english only’ and ‘anglais seulement’ to the french page just like you did with strategies and initiatives pages.

Resources page changes

---

.github/workflows/github-project-export.yml

Having time in the file name adds multiple : to the filename which causes problems with windows machines running local clones

remove time from the RUN_DATE variable

---

.markdown-link-check.json
_pages/en/strategy-open-first.md

- removed the 2 deadlinks to the EU site in the Open first paper.
- Added twitter.com to the exclusions list of the link checker.
Note: other people seem to also be having an issue with twitter.com and the markdown-link-check. Trying to apply the only identified fix didn't work for our twitter links. Also there are way too many twitter links in all our pages and posts. Easiest is just to exclude Twitter.  https://github.com/tcort/markdown-link-check/issues/199

Fix dead link issue

---

package-lock.json
package.json

Package.json
- Change devDependencies for mark-down-link from “^3..10.3” (https://github.com/tcort/markdown-link-check) to https://github.com/thebiggest0/markdown-link-check.
- Reason: To prevent an error from being thrown when a broken link is encountered, the javascript in markdown-link-check needed to be changed. And for the change to be retained for future use this was the solution I found.
Package-lock.json
- Update content to reflect changes made to package.json (through npm install).
- Changes: mark-down-link resolved points to https://github.com/thebiggest0/markdown-link-check instead of the original registry on http://npmjs.org/.
- Changes: The version is now 3.10.4 (before 3.10.3) to reflect the changes I made in the markdown-link-check file. In the function …

Update package.json and package-lock.json so test script warns on broken links

---

.github/workflows/link-check.yml
package-lock.json
package.json

Package.json & Package-lock.json
- Update devDependencies in package.json to point to markdown-link-check GitHub repository in sara-sabr.
- Update package-lock.json according to package.json
GitHub actions: link-check.yml
- Add npm ci
- Update run: npm run weekly-link-check

Update markdown-link-check dependency and weekly link check test

---

.github/workflows/link-check.yml
.github/workflows/node.js.yml
data.json
package-lock.json
package.json
validate-broken-link.js

validate-broken-link.js
- Add a new JavaScript file containing functions to validate broken link
data.json
- Add a new JSON file to keep a record of all broken links and the dates associated with each
package.json and package-lock.json
- Update markdown-link-check dependencies to the newest version that reads and writes to data.json
GitHub workflows
- Update node.js.yml and link-check.yml to allow GitHub actions to commit changes to data.json when broken links are detected

Added Broken link validation feature
